/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backup;

import Backup.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author USER
 */
public class F2 extends javax.swing.JFrame {

    /**
     * Creates new form F2
     */
     F3 obj = new F3();
     
    public F2() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P4 = new javax.swing.JPanel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        L6 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        L7 = new javax.swing.JLabel();
        T5 = new javax.swing.JTextField();
        L8 = new javax.swing.JLabel();
        T6 = new javax.swing.JTextField();
        B3 = new javax.swing.JButton();
        PU1 = new javax.swing.JPasswordField();
        PU2 = new javax.swing.JPasswordField();
        PW1 = new javax.swing.JLabel();
        PW2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PA = new javax.swing.JPanel();
        LA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P4.setBackground(new java.awt.Color(204, 204, 255));
        P4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        P4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L3.setText("Name");
        P4.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 80, 20));

        L4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L4.setText("Meter No");
        P4.add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 119, 20));

        L5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L5.setText("Mobile No");
        P4.add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        T1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        P4.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 326, 30));

        T2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        P4.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 326, 30));

        T3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        P4.add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 326, 30));

        L6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L6.setText("Consumer No");
        P4.add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));

        T4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        P4.add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 326, 30));

        L7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L7.setText("Address");
        P4.add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 161, 20));

        T5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        T5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T5ActionPerformed(evt);
            }
        });
        P4.add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 326, 30));

        L8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L8.setText("Card No");
        P4.add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, 20));

        T6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6ActionPerformed(evt);
            }
        });
        P4.add(T6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 326, 30));

        B3.setBackground(new java.awt.Color(0, 0, 255));
        B3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B3.setForeground(new java.awt.Color(255, 51, 0));
        B3.setText("Login");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        P4.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 140, 60));

        PU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU1ActionPerformed(evt);
            }
        });
        P4.add(PU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 320, 30));

        PU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU2ActionPerformed(evt);
            }
        });
        P4.add(PU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 320, 30));

        PW1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PW1.setText("Set Password");
        P4.add(PW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 20));

        PW2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PW2.setText("Confirm Password");
        P4.add(PW2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, 20));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        P4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 140, 60));

        getContentPane().add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 730, 640));

        PA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51), 3));

        LA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LA.setText("Enter ur details-");

        javax.swing.GroupLayout PALayout = new javax.swing.GroupLayout(PA);
        PA.setLayout(PALayout);
        PALayout.setHorizontalGroup(
            PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PALayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(LA)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        PALayout.setVerticalGroup(
            PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LA)
                .addGap(41, 41, 41))
        );

        getContentPane().add(PA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 50));

        setSize(new java.awt.Dimension(750, 736));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void T6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T6ActionPerformed
  
    public int Add_data() throws SQLException
    {
        int flag=0;
        try
                {
                    
                    String s1,s2,s3,s4,s5,s6,s7,s8,s9;
                    Class.forName("com.mysql.jdbc.Driver");
	            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/MP","root","tiger");
		    PreparedStatement ps = cn.prepareStatement("INSERT INTO Customer VALUES(?,?,?,?,?,?,?);");
                    s1 = this.T1.getText();
		    
                    int pnum;
                    s2 = this.T3.getText();
                   
                    s3 = this.T4.getText();
                    s4= this.T6.getText();
                    int card_n;
                    
		    s5 = this.T5.getText();
                    int me_n;
                    s6 = this.T2.getText();
                   
                    
                    s7 =this.PU1.getText();
                    
                    s8 =  this.PU2.getText();
                    if(s1.isEmpty()||s2.isEmpty()||s3.isEmpty()||s4.isEmpty()||s5.isEmpty()||s6.isEmpty()||s7.isEmpty()||s8.isEmpty())
                    {
                        
                         JOptionPane.showMessageDialog(null,"All fields are compulsory to be filled", "Incorrect Details", JOptionPane.WARNING_MESSAGE);
                     
                    }
                    
                   
                    else{
                        
                        try{
                         pnum = Integer.parseInt(s2);
                          int consum_n = Integer.parseInt(s3);
                   card_n= Integer.parseInt(s4);
                    me_n = Integer.parseInt(s6);
                    ps.setString(1,s1);
		    ps.setInt(2,pnum);
                    ps.setInt(3,consum_n);
                    ps.setInt(4,card_n);
                    ps.setString(5, s5);  
                    ps.setInt(6, me_n);
                    ps.setString(7, s7);
                        }
                        
                        catch(Exception e)
                        {
                                       JOptionPane.showMessageDialog(null,"Please enter integer ", "Incorrect data", JOptionPane.WARNING_MESSAGE);
                   
                        }
                    }
                     
                    System.out.println("s7="+s7+"\ts8="+s8);
            
                    if(!s7.equals(s8))
                    {
                              JOptionPane.showMessageDialog(null,"Both passwords must be same", "Incorrect Details", JOptionPane.WARNING_MESSAGE);
                    }
                   
       
                      
                    else  
                    {
                        ps.executeUpdate();
                        flag=1;
                    }
                    
                    
                }
                catch(Exception e)
                {
                    System.out.println("Exception => "+e);
                }
        return flag;
    }
    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here
       int flag=0;
       try
        {
           int c= this.Add_data();
           if(c==1) 
           {
               this.dispose(); 
               obj.setVisible(true);
        obj.T7.setText(this.T1.getText());
        obj.T8.setText(this.T2.getText());
        obj.T9.setText(this.T3.getText());
        obj.T10.setText(this.T4.getText());
        obj.T11.setText(this.T5.getText());
        obj.T12.setText(this.T6.getText()); 
           }
        }
        
        catch(Exception e)  
        {
            System.out.println("Exception => "+e);
        }
       
       
       
         
        
        
       
       
          
       
    }//GEN-LAST:event_B3ActionPerformed

    private void PU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU2ActionPerformed
        // TODO add your handling code here:
        String n1 = PU1.getText();
       String n2 = PU2.getText();
       if(!n1.equals(n2))
       {
             
        System.out.println("N1="+n1);
        System.out.println("N2="+n2);
        JOptionPane.showMessageDialog(null,"Enter corect password", "Incorrect password", JOptionPane.WARNING_MESSAGE);        
       }
       
    }//GEN-LAST:event_PU2ActionPerformed

    private void PU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PU1ActionPerformed

    private void T5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.T1.setText("");
        this.T2.setText("");
        this.T3.setText("");
        this.T4.setText("");
        this.T5.setText("");
        this.T6.setText("");
        this.PU1.setText("");
        this.PU2.setText("");

        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE P3ot available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
       
            
        EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                String s;
                F2 f2 = new F2();
                f2.setVisible(true);/*
                try
                {
                    Class.forName("com.mysql.jdbc.Driver");
	            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/MP","root","tiger");
		    PreparedStatement ps = cn.prepareStatement("INSERT INTO Customer VALUES(?,?,?,?,?,?,?);");
                    s = f2.T1.getText();
		    ps.setString(1,s);
                    int pnum;
                    s = f2.T3.getText();
                    pnum = Integer.parseInt(s);
		    ps.setInt(2,pnum);
                    s = f2.T4.getText();
                    int consum_n = Integer.parseInt(s);
                    ps.setInt(3,consum_n);
                    s= f2.T6.getText();
                    int card_n;
                    card_n= Integer.parseInt(s);
		    ps.setInt(4,card_n);
                    s = f2.T5.getText();
                    ps.setString(5, s);
                    int mob_n;
                    s = f2.T3.getText();
                    mob_n = Integer.parseInt(s);
                    ps.setInt(6, mob_n);
                    s = f2.PU1.getText();
                    ps.setString(7, s);
		    ps.executeUpdate();
                }
                catch(Exception e)
                {
                    System.out.println("Exception => "+e);
                }*/
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B3;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel LA;
    private javax.swing.JPanel P4;
    private javax.swing.JPanel PA;
    private javax.swing.JPasswordField PU1;
    private javax.swing.JPasswordField PU2;
    private javax.swing.JLabel PW1;
    private javax.swing.JLabel PW2;
    protected javax.swing.JTextField T1;
    protected javax.swing.JTextField T2;
    protected javax.swing.JTextField T3;
    protected javax.swing.JTextField T4;
    protected javax.swing.JTextField T5;
    protected javax.swing.JTextField T6;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
