/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backup;

import Backup.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class F4 extends javax.swing.JFrame {

    /**
     * Creates new form F4
     */
   // F3 obj = new F3();
    public F4() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P7 = new javax.swing.JPanel();
        L9 = new javax.swing.JLabel();
        P8 = new javax.swing.JPanel();
        L21 = new javax.swing.JLabel();
        T13 = new javax.swing.JTextField();
        L11 = new javax.swing.JLabel();
        L20 = new javax.swing.JLabel();
        PSW1 = new javax.swing.JPasswordField();
        L22 = new javax.swing.JLabel();
        T14 = new javax.swing.JTextField();
        B5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P7.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5)));

        L9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        L9.setText("System Login");

        javax.swing.GroupLayout P7Layout = new javax.swing.GroupLayout(P7);
        P7.setLayout(P7Layout);
        P7Layout.setHorizontalGroup(
            P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P7Layout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addComponent(L9)
                .addGap(307, 307, 307))
        );
        P7Layout.setVerticalGroup(
            P7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L9, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(P7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 130));

        P8.setBackground(new java.awt.Color(153, 153, 255));
        P8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 153), 5));

        L21.setBackground(new java.awt.Color(0, 0, 0));
        L21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L21.setText("Enter ConsumerNo");

        T13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T13ActionPerformed(evt);
            }
        });

        L11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L11.setText("OR");

        L20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L20.setText("Enter Password");

        PSW1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        L22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L22.setText("Enter CardNo");

        T14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        B5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B5.setText("Submit");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\ps2.jpeg")); // NOI18N

        javax.swing.GroupLayout P8Layout = new javax.swing.GroupLayout(P8);
        P8.setLayout(P8Layout);
        P8Layout.setHorizontalGroup(
            P8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P8Layout.createSequentialGroup()
                .addGroup(P8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P8Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(P8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P8Layout.createSequentialGroup()
                                .addGroup(P8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(P8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(L22)
                                        .addGroup(P8Layout.createSequentialGroup()
                                            .addGroup(P8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(L20, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(L21))
                                            .addGap(123, 123, 123)
                                            .addComponent(PSW1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(T13, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1))
                            .addGroup(P8Layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(T14, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(P8Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(L11))
                    .addGroup(P8Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        P8Layout.setVerticalGroup(
            P8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(P8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PSW1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(P8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P8Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(L21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P8Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(T13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(P8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(L11)
                        .addGap(32, 32, 32)
                        .addComponent(L22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P8Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(T14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(P8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 950, 540));

        setSize(new java.awt.Dimension(970, 719));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void T13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T13ActionPerformed

    public int User_Authentication()throws SQLException
    {
        String s;
        int card_number;
        int flag=0;
        int consumer_number;
         s = PSW1.getText();
         try
         {   
            // Class.forName("com.mysql.jdbc.Driver");
	     Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/MP","root","tiger");
             // System.out.println("sdfsdf");
             PreparedStatement p1 = cn.prepareStatement("SELECT *FROM Customer WHERE Pw = "+"\""+s+"\"");
             //"\"Hello\""
	     ResultSet rs = p1.executeQuery();
             rs.beforeFirst();
             rs.next();
             String s1 = rs.getString("Pw");     
             
             if(!s.equals(s1))
             {
                     JOptionPane.showMessageDialog(null,"Enter correct Password", "Incrrect Password", JOptionPane.WARNING_MESSAGE);
             }
             else
             {
            // card_number=Integer.parseInt(rs.getString("Cano"));
                 card_number = rs.getInt("Cano");
                 System.out.println("Card => "+card_number);
             
             //consumer_number = Integer.parseInt(rs.getString("Cono"));
             consumer_number = rs.getInt("Cono");
             int c1=0,c2=0;
             
             
             if(T13.getText().length()>0)   
             {
                 c1= Integer.parseInt(T13.getText());
                 if(c1!=consumer_number)
                 {
                     JOptionPane.showMessageDialog(null,"Enter correct Consumer number", "Incrrect Consumer number", JOptionPane.WARNING_MESSAGE);
                 }
                 else 
                 {
                  flag=1;
                  
                 }
                 
             }
               
             
             if(T14.getText().length()>0)
             {
                
                 c2 = Integer.parseInt(T14.getText());
                 System.out.println("Card => "+c2);
                 if(c2!=card_number)
                 {
                     
                     JOptionPane.showMessageDialog(null,"Enter correct Card Number", "Incrrect Card Number", JOptionPane.WARNING_MESSAGE);
                 }
                 else flag=1;
                
             }
             }    
         }
         
         catch(Exception e)
         {
            
                 System.out.println("EXCxfdf => "+e);  
         }   
        return flag;
    }
    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:  
        int res=0;   
        
        if(this.PSW1.getText().isEmpty())
        {
              JOptionPane.showMessageDialog(null,"Please enter password", "Error", JOptionPane.WARNING_MESSAGE);
             
        }
        else{
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            res=this.User_Authentication();
            if(res==1)
        {
            JOptionPane.showMessageDialog(null,"Login was successful", "LOGGEDIN!", JOptionPane.INFORMATION_MESSAGE);
             
             int Con=0,CD=0;
            if(this.T13.getText().length()>0)
            {
             Con = Integer.parseInt(this.T13.getText());
             
            }
            
            else
            {
                 if(this.T14.getText().length()>0)
                 {
                    CD = Integer.parseInt(this.T14.getText());
                 }
            }
                  System.out.println("no = "+Con);
              
	     Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/MP","root","tiger");
             PreparedStatement p2;
             if(Con!=0)
             {
                  p2 = cn.prepareStatement("SELECT *FROM Customer WHERE Cono = "+Con);
             }
             else  
             {
                 Con=CD;
                  p2 = cn.prepareStatement("SELECT *FROM Customer WHERE Cano = "+Con);  
             }
             //PreparedStatement p2 = cn.prepareStatement("SELECT *FROM Customer WHERE Cono = "+Con);
             F3 f3 = new F3();
             f3.setVisible(true);      
             
             ResultSet rs1 = p2.executeQuery();
             rs1.next();
             String s = rs1.getString("Name");
             
             f3.T7.setText(s);
             System.out.println(s);
             s = rs1.getString("Adr");
             f3.T11.setText(s);
             System.out.println(s);
             int n = Integer.parseInt(rs1.getString("Mno"));
             f3.T8.setText(n + "");
             System.out.println(n);
             n = Integer.parseInt(rs1.getString("Pno"));
             f3.T9.setText(n+"");
             System.out.println(n);
             n= Integer.parseInt(rs1.getString("Cono"));
             f3.T10.setText(n+"");
             System.out.println(n);
             n = Integer.parseInt(rs1.getString("Cano"));
             f3.T12.setText(n+"");
             System.out.println(n);
             this.dispose();
        }
             
            else
            {
                     JOptionPane.showMessageDialog(null,"Login was not successful", "Inorrect Login", JOptionPane.WARNING_MESSAGE);
            }
        
        }
        
        catch(Exception e)
        {
            System.out.println("EXCerere => "+e);
        }
        
        
        this.dispose();
        }
    }//GEN-LAST:event_B5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B5;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L20;
    private javax.swing.JLabel L21;
    private javax.swing.JLabel L22;
    private javax.swing.JLabel L9;
    private javax.swing.JPanel P7;
    private javax.swing.JPanel P8;
    private javax.swing.JPasswordField PSW1;
    private javax.swing.JTextField T13;
    private javax.swing.JTextField T14;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
