/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backup;

import Backup.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class F5 extends javax.swing.JFrame {

    /**
     * Creates new form F5
     */
    int card_no;
    public F5() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CP2 = new javax.swing.JPanel();
        L5 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        TC2 = new javax.swing.JTextField();
        TC3 = new javax.swing.JTextField();
        TC4 = new javax.swing.JTextField();
        TC5 = new javax.swing.JTextField();
        TC1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        PS = new javax.swing.JLabel();
        PS1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CL1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CP2.setBackground(new java.awt.Color(0, 153, 153));
        CP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 7));
        CP2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L5.setText("Mobile No");
        CP2.add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 40));

        L3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L3.setText("Name");
        CP2.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 70, 48));

        L4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L4.setText("Meter No");
        CP2.add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 119, 30));

        L6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L6.setText("Consumer No");
        CP2.add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 40));

        L7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L7.setText("Address");
        CP2.add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 100, 39));

        TC2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CP2.add(TC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 200, 30));

        TC3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CP2.add(TC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 200, 30));

        TC4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CP2.add(TC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 200, 30));

        TC5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CP2.add(TC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 200, 30));

        TC1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CP2.add(TC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 200, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        CP2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 180, 70));

        PS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PS.setText("Password");
        CP2.add(PS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        PS1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CP2.add(PS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 200, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        CP2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 180, 70));

        getContentPane().add(CP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 690, 560));

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CL1.setBackground(new java.awt.Color(153, 0, 0));
        CL1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CL1.setForeground(new java.awt.Color(204, 0, 51));
        CL1.setText(" ENTER DETAILS FOR CARD");
        CL1.setToolTipText("");
        jPanel2.add(CL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));
        CL1.getAccessibleContext().setAccessibleName("ENTER DETAILS FOR CAR");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 90));

        setSize(new java.awt.Dimension(709, 698));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_cardData() throws SQLException
    {
        try
        {
                    Class.forName("com.mysql.jdbc.Driver");
	            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/MP","root","tiger");
                    this.card_no=0;
        String temp = this.TC1.getText();
        for(int i=0;i<temp.length();i++)
        {
            card_no += temp.charAt(i);
        }
		    PreparedStatement ps = cn.prepareStatement("INSERT INTO Customer VALUES(?,?,?,?,?,?,?);");
                    String s =null;
                     s = this.TC1.getText();
		    ps.setString(1,s);
                    int pnum;
                    s = this.TC3.getText();
                    pnum = Integer.parseInt(s);
		    ps.setInt(2,pnum);
                    s = this.TC4.getText();
                    int consum_n = Integer.parseInt(s);
                    ps.setInt(3,consum_n);
                    ps.setInt(4,card_no);
                    s = this.TC5.getText();
                    ps.setString(5, s);
                    int me_n;
                    s = this.TC2.getText();
                    me_n = Integer.parseInt(s);
                    ps.setInt(6, me_n);
                    s =this.PS1.getText();
                    ps.setString(7, s);
		    ps.executeUpdate();
        }
        
        catch(Exception e)
        {
            
        }
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       
       if(this.TC1.getText().isEmpty()||this.TC2.getText().isEmpty()||this.TC3.getText().isEmpty()||this.TC4.getText().isEmpty()||this.PS1.getText().isEmpty()||this.TC5.getText().isEmpty())
       {
             JOptionPane.showMessageDialog(null,"All fields are compulsory to be filled", "Incorrect Details", JOptionPane.WARNING_MESSAGE);
       }
       
       else{
        JOptionPane.showMessageDialog(null,"U will receive card within 3 days", "Request Accepted", JOptionPane.INFORMATION_MESSAGE);
        F3 obj = new F3();
        obj.setVisible(true);
        obj.T7.setText(this.TC1.getText());
        obj.T8.setText(this.TC2.getText());
        obj.T9.setText(this.TC3.getText());
        obj.T10.setText(this.TC4.getText());
        obj.T11.setText(this.TC5.getText());
        //this.card_no=1001;
        this.card_no=0;
        String temp = this.TC1.getText();
        for(int i=0;i<temp.length();i++)
        {
            card_no += temp.charAt(i);
        }
        System.out.println("Card number => "+this.card_no);
        obj.T12.setText(String.valueOf(this.card_no));
        //obj.T12.setText(this.TC6.getText()); 
        try
        {
            this.add_cardData();
        }
        
        catch (Exception e)
        {
            
        }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.TC1.setText("");
        this.TC2.setText("");
        this.TC3.setText("");
        this.TC4.setText("");
        this.TC5.setText("");
        this.PS1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CL1;
    private javax.swing.JPanel CP2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel PS;
    private javax.swing.JPasswordField PS1;
    private javax.swing.JTextField TC1;
    private javax.swing.JTextField TC2;
    private javax.swing.JTextField TC3;
    private javax.swing.JTextField TC4;
    private javax.swing.JTextField TC5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
