/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backup;

import Backup.*;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;

/**
 *
 * @author USER
 */
public class F6 extends javax.swing.JFrame {

    /**
     * Creates new form F6
     */
    int connum;
    public F6() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P30 = new javax.swing.JPanel();
        CL1 = new javax.swing.JLabel();
        CN1 = new javax.swing.JTextField();
        JP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        PW1 = new javax.swing.JLabel();
        MN = new javax.swing.JTextField();
        SP = new javax.swing.JTextField();
        ADRS = new javax.swing.JTextField();
        CheckBalance = new javax.swing.JButton();
        Recharge = new javax.swing.JButton();
        UINFO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P30.setBackground(new java.awt.Color(153, 153, 153));
        P30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        P30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CL1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CL1.setForeground(new java.awt.Color(204, 0, 51));
        CL1.setText("Enter Consumer Number");
        P30.add(CL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 44));

        CN1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CN1ActionPerformed(evt);
            }
        });
        P30.add(CN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 13, 316, 44));

        getContentPane().add(P30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        JP.setBackground(new java.awt.Color(153, 153, 255));
        JP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 255), 7));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Edit info -");

        L5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        L5.setText("Mobile No");

        L7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        L7.setText("Address");

        PW1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        PW1.setText("Set Password");

        MN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        SP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPActionPerformed(evt);
            }
        });

        ADRS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        CheckBalance.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CheckBalance.setText("Balance-Enquiry");
        CheckBalance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        CheckBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBalanceActionPerformed(evt);
            }
        });

        Recharge.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Recharge.setText("Recharge");
        Recharge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        Recharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechargeActionPerformed(evt);
            }
        });

        UINFO.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        UINFO.setText("Update-Info");
        UINFO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 10, true));
        UINFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UINFOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPLayout = new javax.swing.GroupLayout(JP);
        JP.setLayout(JPLayout);
        JPLayout.setHorizontalGroup(
            JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPLayout.createSequentialGroup()
                        .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L5)
                            .addComponent(PW1)
                            .addComponent(L7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SP, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(MN, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(ADRS)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPLayout.createSequentialGroup()
                .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(CheckBalance)
                        .addGap(173, 173, 173)
                        .addComponent(Recharge))
                    .addGroup(JPLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(UINFO)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        JPLayout.setVerticalGroup(
            JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(MN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(L5, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADRS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPLayout.createSequentialGroup()
                        .addComponent(PW1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(UINFO)
                        .addGap(36, 36, 36)
                        .addGroup(JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Recharge)
                            .addComponent(CheckBalance)))
                    .addGroup(JPLayout.createSequentialGroup()
                        .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(JP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 980, 600));

        setSize(new java.awt.Dimension(1000, 719));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RechargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechargeActionPerformed
        // TODO add your handling code here:
        
        if(this.CN1.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(null,"Please enter Consumer number", "Error", JOptionPane.ERROR_MESSAGE);
           
        }
        
        else
        connum=Integer.parseInt(this.CN1.getText());    
        
        
        F7 f7 = new F7();
        f7.ccn=connum;  
        f7.setVisible(true); 
    }//GEN-LAST:event_RechargeActionPerformed

    private void CheckBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBalanceActionPerformed
        // TODO add your handling code here:
        
        
         if(this.CN1.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(null,"Please enter Consumer number", "Error", JOptionPane.ERROR_MESSAGE);
           
        }
        
        else
         {
             connum=Integer.parseInt(this.CN1.getText());    
             
             try
        {
              Class.forName("com.mysql.jdbc.Driver");
              Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/MP","root","tiger");
              
              String sql = "SELECT * FROM ENQUIRY WHERE CNO = "+connum;
             
              PreparedStatement ps = cn.prepareStatement(sql);
              
              ResultSet rs = ps.executeQuery();
             
              rs.next();
               double units = rs.getDouble("UNITS");
               
              java.util.Date d2 = rs.getDate("DD");
              java.util.Date d1 = new java.util.Date(); 
                      System.out.println("todays => "+d1);
                      System.out.println("due => "+d2);
                       
              if(d1==d2)
              {
                    System.out.println("Date equal");
              }
              
              else
              {
                  
                  long diff = Math.abs(d2.getTime()-d1.getTime());  
                  diff= diff/86400000;
                  System.out.println("days => "+diff);
                  System.out.println("units initially=>"+units );
                  diff= 30-diff;
                  units -= diff*10;
                    
                  System.out.println("units =>"+units);
                  F8 f8 = new F8();
                  f8.setVisible(true);
                  
                  if(units==0)
                  {
                      f8.EC.setText("0");
                  }
                  if(diff>=25)
                  {
                       JOptionPane.showMessageDialog(null,"Last "+diff+" days are remaining plz recharge as soon as possible", "Warning", JOptionPane.WARNING_MESSAGE);
                  }
                       //JOptionPane.showMessageDialog(null,"Last "+diff+" days are remaining plz recharge as soon as possible", "Warning", JOptionPane.WARNING_MESSAGE);
                  
                  
                  
                  f8.EC.setText(String.valueOf(units));
                  String sql2 = "UPDATE ENQUIRY SET UNITS = "+units+" WHERE CNO = "+connum;
                  //String sql="UPDATE T2 SET ID=0 WHERE NAME='BB'"; 
                  PreparedStatement ps2 = cn.prepareStatement(sql2);  
                  ps2.executeUpdate();
                  
              }
              
              
              
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,"Please recharge to see the balance", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
         }
           
        
            
    }//GEN-LAST:event_CheckBalanceActionPerformed

    private void CN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CN1ActionPerformed
    
    private void update_Info()throws SQLException
    {
        try
        {   
                Class.forName("com.mysql.jdbc.Driver");
		Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/MP","root","tiger");
                String s=null;  
                int cno = Integer.parseInt(this.CN1.getText());
                s= this.MN.getText();
                int no = Integer.parseInt(s);
                String sql = "UPDATE CUSTOMER SET  Pno = "+no+" WHERE Cono = "+cno+";";
                PreparedStatement ps = cn.prepareStatement(sql);
                ps.executeUpdate();
                s = this.ADRS.getText();
                //"\"ROM\""
                //        quoteText = "\"" + myText + "\"";
                sql = "UPDATE CUSTOMER SET  Adr = \""+ s +"\""+" WHERE Cono = "+cno+";";
                ps.executeUpdate(sql);
                s = this.SP.getText();
                sql = "UPDATE CUSTOMER SET  Pw = \""+ s +"\""+" WHERE Cono= "+cno+";";
                ps.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Info updated", "Updated", JOptionPane.INFORMATION_MESSAGE);
             
        }
        catch(Exception e)
        {
            
        }
                
    }
    private void UINFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UINFOActionPerformed
        // TODO add your handling code here:
        try{
        this.update_Info();
        }
        
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_UINFOActionPerformed

    private void SPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADRS;
    private javax.swing.JLabel CL1;
    public javax.swing.JTextField CN1;
    private javax.swing.JButton CheckBalance;
    private javax.swing.JPanel JP;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L7;
    private javax.swing.JTextField MN;
    private javax.swing.JPanel P30;
    private javax.swing.JLabel PW1;
    private javax.swing.JButton Recharge;
    private javax.swing.JTextField SP;
    private javax.swing.JButton UINFO;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
