/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backup;

import Backup.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import java.time.LocalDate;

/**
 *
 * @author USER
 */
public class F7 extends javax.swing.JFrame {

    /**
     * Creates new form F7
     */
    Date recharge_date,due_date;
    java.sql.Date rdate,ddate;
    int ccn;
    public F7()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        RCHG = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 7));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Recharge");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));

        RCHG.setBackground(new java.awt.Color(51, 51, 51));
        RCHG.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        RCHG.setForeground(new java.awt.Color(204, 0, 0));
        RCHG.setText("OFFER1");
        RCHG.setActionCommand("");
        RCHG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCHGActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("OFFER2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("600 Units/Month");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("300 Units/Month");

        LO.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LO.setText("Logout");
        LO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel2)
                        .addContainerGap(152, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RCHG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(175, 175, 175))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(LO)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RCHG, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(LO)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(869, 654));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null,"Recharge was successful", "Done", JOptionPane.INFORMATION_MESSAGE);
          recharge_date = new Date();
          Calendar cal = Calendar.getInstance();
          cal.add(Calendar.DAY_OF_MONTH, 30);
          due_date = cal.getTime();
          
         try
         {
             
             System.out.println("rech in util =>"+recharge_date);
             System.out.println("due date in util =>"+due_date);
              Class.forName("com.mysql.jdbc.Driver");
              Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/MP","root","tiger");
              rdate = new java.sql.Date(recharge_date.getTime());
              ddate = new java.sql.Date(due_date.getTime());
              String sql2 = "INSERT INTO ENQUIRY (CNO) VALUES ("+ccn+ ")";
              //String sql="UPDATE T2 SET ID=0 WHERE NAME='BB'"; 
              PreparedStatement ps2 = cn.prepareStatement(sql2);  
              ps2.executeUpdate();
             // String sql1 = "INSERT INTO ENQUIRY(Rd,DD) VALUES('"+rdate+"','"+ddate+"')";
             // ps2 = cn.prepareStatement(sql1);
             String p = "UPDATE ENQUIRY SET Rd = '"+rdate+"' WHERE CNO = "+ccn;
              //ps2.executeUpdate();
              ps2 = cn.prepareStatement(p);
              ps2.executeUpdate();
              String p1 = "UPDATE ENQUIRY SET DD = '"+ddate+"' WHERE CNO = "+ccn;
              ps2 = cn.prepareStatement(p1);
              ps2.executeUpdate();
              String p2 ="UPDATE ENQUIRY SET UNITS = 600 WHERE CNO = "+ccn;
              ps2 = cn.prepareStatement(p2);
              ps2.executeUpdate();
         }
              catch(Exception e)
         {
             
         }
           
              
              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void RCHGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCHGActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Recharge was successful", "Done", JOptionPane.INFORMATION_MESSAGE);
          recharge_date = new Date();
          Calendar cal = Calendar.getInstance();
          cal.add(Calendar.DAY_OF_MONTH, 30);
          due_date = cal.getTime();
          
         try
         {
             
             System.out.println("rech in util =>"+recharge_date);
             System.out.println("due date in util =>"+due_date);
              Class.forName("com.mysql.jdbc.Driver");
              Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/MP","root","tiger");
              rdate = new java.sql.Date(recharge_date.getTime());
              ddate = new java.sql.Date(due_date.getTime());
              String sql2 = "INSERT INTO ENQUIRY (CNO) VALUES ("+ccn+ ")";
              //String sql="UPDATE T2 SET ID=0 WHERE NAME='BB'"; 
              PreparedStatement ps2 = cn.prepareStatement(sql2);
              ps2.executeUpdate();
             // String sql1 = "INSERT INTO ENQUIRY(Rd,DD) VALUES('"+rdate+"','"+ddate+"')";
             // ps2 = cn.prepareStatement(sql1);
             String p = "UPDATE ENQUIRY SET Rd = '"+rdate+"' WHERE CNO = "+ccn;
              //ps2.executeUpdate();
              ps2 = cn.prepareStatement(p);
              ps2.executeUpdate();
              String p1 = "UPDATE ENQUIRY SET DD = '"+ddate+"' WHERE CNO = "+ccn;
              ps2 = cn.prepareStatement(p1);
              ps2.executeUpdate();
              String p2 ="UPDATE ENQUIRY SET UNITS = 300 WHERE CNO = "+ccn;
              ps2 = cn.prepareStatement(p2);
              ps2.executeUpdate();
              
              
         }
         
         catch(Exception e)
         {
             
         }
    }//GEN-LAST:event_RCHGActionPerformed

    private void LOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOActionPerformed
        // TODO add your handling code here:
        F1 f1 = new F1();
        f1.setVisible(true);
    }//GEN-LAST:event_LOActionPerformed
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LO;
    private javax.swing.JButton RCHG;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
